spring.application.name=travel-agency

# Oracle XE in Docker on localhost
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=travel_lab
spring.datasource.password=travel_lab
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

server.port=8080
